package api

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/DATA-DOG/go-sqlmock"
	"github.com/gorilla/mux"

	"middle-monitor/backend/middleware"
	"middle-monitor/backend/models"
	"middle-monitor/backend/services"
)

func nowUTC() time.Time { return time.Now().UTC() }

func errNoRows() error { return sql.ErrNoRows }

// adminRequest builds an authenticated org-scoped request whose session carries
// the admin role, for the routes that gate on it.
func adminRequest(method, target, body string) *http.Request {
	r := httptest.NewRequest(method, target, strings.NewReader(body))
	claims := &services.JWTClaims{OrganizationID: 1, UserID: 7, Role: "admin", Email: "admin@example.com"}
	return r.WithContext(context.WithValue(r.Context(), middleware.ClaimsContextKey, claims))
}

// stubChatCompletion serves one canned OpenAI-compatible answer and returns its
// base URL.
func stubChatCompletion(t *testing.T, body string) string {
	t.Helper()
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		_, _ = w.Write([]byte(body))
	}))
	t.Cleanup(server.Close)
	return server.URL
}

// muxVars attaches path variables to a request, as the router would.
func muxVars(r *http.Request, vars map[string]string) *http.Request {
	return mux.SetURLVars(r, vars)
}

// seenArg is a sqlmock argument that matches anything and records that it was
// compared, so a test can assert a statement ran without having to predict how
// many other statements the code under test issues.
type seenArg struct{ hit *bool }

func (a seenArg) Match(driver.Value) bool {
	*a.hit = true
	return true
}

func nullInt(v int64) sql.NullInt64 { return sql.NullInt64{Int64: v, Valid: true} }

func incidentWithService(serviceID *int64) models.Incident {
	return models.Incident{ServiceID: serviceID}
}

// sqlmockDB pairs a mock database with its expectation recorder, so a table
// driven test can build one per case without repeating the wiring.
type sqlmockDB struct {
	*sql.DB
	mock sqlmock.Sqlmock
}

// orgRequest builds an authenticated org-scoped request with the given mux vars.
func orgRequest(method, target, body string, vars map[string]string) *http.Request {
	var r *http.Request
	if body == "" {
		r = httptest.NewRequest(method, target, nil)
	} else {
		r = httptest.NewRequest(method, target, strings.NewReader(body))
	}
	r = orgContext(r, 1, 7)
	if vars != nil {
		r = mux.SetURLVars(r, vars)
	}
	return r
}

// A host scope that matches nothing must return nothing: silently widening to
// the whole org would show another host's metrics under a host filter.
func TestSeriesHostScopeNeverWidensToTheWholeOrg(t *testing.T) {
	db, mock, _ := sqlmock.New()
	defer db.Close()

	names, scoped, ok := seriesHostScope(db, httptest.NewRequest("GET", "/x", nil), 1)
	if scoped || !ok || names != nil {
		t.Fatalf("an unscoped request is not scoped: %v %v %v", names, scoped, ok)
	}

	mock.ExpectQuery("SELECT name FROM hosts WHERE id").WillReturnRows(sqlmock.NewRows([]string{"name"}))
	_, scoped, ok = seriesHostScope(db, httptest.NewRequest("GET", "/x?host_id=4", nil), 1)
	if !scoped || ok {
		t.Fatal("a host scope matching nothing must yield nothing")
	}

	mock.ExpectQuery("SELECT name FROM hosts WHERE host_group_id").
		WillReturnRows(sqlmock.NewRows([]string{"name"}).AddRow("web-01").AddRow("web-02"))
	names, scoped, ok = seriesHostScope(db, httptest.NewRequest("GET", "/x?host_group_id=2", nil), 1)
	if !scoped || !ok || len(names) != 2 {
		t.Fatalf("group scope resolved to %v", names)
	}

	mock.ExpectQuery("SELECT name FROM hosts").WillReturnError(errors.New("down"))
	_, scoped, ok = seriesHostScope(db, httptest.NewRequest("GET", "/x?host_id=4", nil), 1)
	if !scoped || ok {
		t.Fatal("a failed scope lookup must not widen the query either")
	}
}

// The unsubscribe link is generated by the outreach sender in another language.
// This value was produced by that sender: if this test fails, valid opt-outs are
// being rejected, which is the one failure mode with legal consequences.
func TestUnsubscribeTokenMatchesTheSender(t *testing.T) {
	got := unsubscribeToken("contact@acme.fr", "s3cr3t")
	if want := "d7290b723c1f31e5"; got != want {
		t.Fatalf("token %q, want %q", got, want)
	}
}
